import { TrainingModule } from '../training-content'

export const trainingModulesZHCN: TrainingModule[] = [
  { id: 1, title: '高效投注者的不同之处', slug: 'what-effective-bettors-do-differently', description: '学习将有纪律的投注者与休闲玩家区分开来的心态和行为。', sections: [{ title: '市场参与者心态', content: '大多数投注者像赌场访客一样接近市场——他们寻找娱乐、刺激和赢钱的机会。有纪律的投注者完全不同地看待市场。他们理解自己正在参与一个竞争性市场，成功取决于持续做出比其他参与者更好的评估。' }, { title: '选择性而非行动', content: '高效投注者与普通玩家之间最明显的区别之一是投注数量。普通投注者经常觉得需要对他们观看的每场比赛下注。有纪律的投注者理解每次投注都需要优势，而优势不会按时间表出现。' }, { title: '真正的工作描述', content: '投注者的工作不是预测赢家——而是比市场更准确地评估概率，并识别定价错误的时机。' }, { title: '什么区分了有纪律的投注者', content: '有纪律的投注者有几个共同特点：他们保留详细记录，理解方差，设定明确规则并遵守它们。' }, { title: '为什么本手册故意很长', content: '本手册内容全面，因为真正理解投注需要深度。快速技巧和"稳赢"长期不起作用。' }, { title: '投注者运营周期', content: '有效投注遵循一个明确的周期：研究、市场比较、价值识别、投注额确定、执行、记录、回顾。' }] },
  { id: 2, title: '博彩公司、交易所和投注市场的真正运作方式', slug: 'how-bookmakers-exchanges-and-betting-markets-really-work', description: '了解投注市场的结构，赔率如何设定，以及你的钱实际来自哪里。', sections: [{ title: '博彩公司的商业模式', content: '博彩公司不是你对抗的对手——他们是试图平衡账本并收取利润的企业。' }, { title: '投注交易所vs传统博彩公司', content: '像Betfair这样的投注交易所运作方式不同。你不是与博彩公司对赌，而是与其他玩家对赌。' }, { title: '赔率如何变动', content: '赔率不是静态的。它们随着资金流动、新闻和市场力量不断变化。' }, { title: '理解利润率', content: '每家博彩公司都在赔率中包含利润率。这意味着如果你将所有赔率转换为概率，它们的总和会超过100%。' }] },
  { id: 3, title: '赔率、隐含概率和公平定价', slug: 'odds-implied-probability-and-fair-pricing', description: '掌握将赔率转换为概率和识别价值的数学基础。', sections: [{ title: '理解赔率格式', content: '赔率以三种主要格式呈现：小数、分数和美式。' }, { title: '转换为隐含概率', content: '每个赔率都隐含一个概率。公式：隐含概率 = 1 / 小数赔率 × 100%' }, { title: '去除利润率找到公平赔率', content: '博彩公司的赔率包含利润率。要找到"公平"赔率，你需要去除这个利润率。' }] },
  { id: 4, title: '价值、期望值、比较赔率和收盘线价值', slug: 'value-expected-value-line-shopping-and-closing-line-value', description: '理解价值概念、期望值以及为什么击败收盘赔率是最重要的指标。', sections: [{ title: '价值真正意味着什么', content: '投注中的价值简单地意味着你获得的赔率比结果的实际概率所应该给的更好。' }, { title: '期望值(EV)', content: '期望值是你平均每次投注可以期望赢（或输）多少的数学度量。' }, { title: '比较赔率(Line Shopping)', content: '不同的博彩公司对同一事件提供不同的赔率。比较赔率意味着寻找最佳赔率。' }, { title: '收盘线价值(CLV)', content: '收盘线是事件开始前的赔率。CLV衡量你获得比收盘线更好赔率的频率。' }] },
  { id: 5, title: '资金管理、投注额和在方差中生存', slug: 'bankroll-management-staking-and-survival-under-variance', description: '学习保护你的资本并优化投注额以获得长期成功。', sections: [{ title: '为什么资金管理至关重要', content: '你可能擅长发现价值，但没有适当的资金管理，你仍然会失去一切。' }, { title: '投注方法', content: '固定投注、百分比投注、凯利准则——每种都有其优势。' }, { title: '理解方差', content: '方差意味着短期内任何事情都可能发生。' }] },
  { id: 6, title: '完整的投注者工作流程', slug: 'the-full-bettor-workflow-from-fixture-list-to-placed-bet', description: '学习识别机会和下注的系统过程。', sections: [{ title: '步骤1：市场扫描', content: '从每日市场扫描开始。' }, { title: '步骤2：初步分析', content: '识别你看到潜在价值的比赛。' }, { title: '步骤3：深入研究', content: '对有前景的目标深入挖掘。' }, { title: '步骤4：价值确认', content: '将你的最终概率估计与可用赔率比较。' }, { title: '步骤5：执行和记录', content: '以最佳可用赔率下注并立即记录。' }] },
  { id: 7, title: '足球课程', slug: 'football-class', description: '深入足球投注。', sections: [{ title: '足球市场概述', content: '足球是世界上最大的投注市场。' }, { title: '关键分析因素', content: '预期进球、阵容变化、动机、条件。' }, { title: '热门市场', content: '1X2、亚洲盘、大小球、双方进球。' }] },
  { id: 8, title: '赛马课程', slug: 'horse-racing-class', description: '学习赛马投注的特点。', sections: [{ title: '赛马市场特点', content: '赛马是需要专业化的传统投注运动。' }, { title: '分析基础', content: '状态、条件、距离、级别。' }] },
  { id: 9, title: '网球课程', slug: 'tennis-class', description: '网球投注策略。', sections: [{ title: '网球特点', content: '网球是个人运动。' }, { title: '关键因素', content: '场地、直接对决、锦标赛阶段、伤病。' }] },
  { id: 10, title: '篮球课程', slug: 'basketball-class', description: 'NBA和欧洲篮球投注。', sections: [{ title: '篮球市场', content: '篮球是高分运动。' }, { title: '关键分析因素', content: '四因素模型、节奏、缺阵。' }] },
  { id: 11, title: '冰球课程', slug: 'ice-hockey-class', description: 'NHL和欧洲冰球投注。', sections: [{ title: '冰球市场特点', content: '冰球是低分高方差运动。' }, { title: '关键分析因素', content: 'Corsi/Fenwick、特殊团队、背靠背。' }] },
  { id: 12, title: '棒球课程', slug: 'baseball-class', description: 'MLB投注基础。', sections: [{ title: '棒球特点', content: '棒球是最以统计为导向的运动。' }, { title: '分析工具', content: 'Sabermetrics: WAR, FIP, wOBA。' }] },
  { id: 13, title: '美式足球课程', slug: 'american-football-class', description: 'NFL和大学橄榄球投注。', sections: [{ title: 'NFL市场', content: 'NFL是美国最受欢迎的投注运动。' }, { title: '关键分析因素', content: 'DVOA、伤病、天气。' }] },
  { id: 14, title: '其他运动和专业细分市场', slug: 'other-sports-and-specialist-niches', description: '不太知名运动中的机会。', sections: [{ title: '细分市场的优势', content: '不太知名的运动和联赛通常提供最好的机会。' }, { title: '示例', content: '电子竞技、乒乓球、飞镖、斯诺克。' }] },
  { id: 15, title: '投注类型大师课', slug: 'bet-types-masterclass', description: '深入了解各种投注类型。', sections: [{ title: '单注vs组合', content: '单注几乎总是更好的选择。' }, { title: '深入亚洲盘', content: '亚洲盘提供更多选择。' }, { title: '特殊投注', content: 'Props、实时投注、期货。' }] },
  { id: 16, title: '个人投注笔记本', slug: 'personal-betting-notebook-decision-log-and-review-record', description: '如何记录投注并从数据中学习。', sections: [{ title: '为什么记录是必要的', content: '没有准确记录，你不知道自己是否真正盈利。' }, { title: '记录什么', content: '日期、时间、比赛、选择、赔率、投注额、结果。' }, { title: '分析', content: '定期审查数据并寻找趋势。' }] },
  { id: 17, title: '绩效评估和结果分析', slug: 'reviewing-performance-maintaining-records-and-learning-from-results', description: '如何评估投注质量。', sections: [{ title: '正确的指标', content: 'ROI和CLV是比胜率更好的指标。' }, { title: '样本量和显著性', content: '短期结果主要是方差。' }] },
  { id: 18, title: '心理、纪律和专业常规', slug: 'psychology-discipline-tilt-control-and-professional-routines', description: '心理控制的重要性。', sections: [{ title: '倾斜及其避免', content: '倾斜意味着你做出糟糕决定的情绪状态。' }, { title: '常规', content: '专业投注者遵循常规。' }, { title: '现实期望', content: '大多数投注者会输。' }] },
  { id: 19, title: '更安全的赌博和自我保护', slug: 'safer-gambling-standards-compliance-awareness-and-personal-protection', description: '如何负责任地玩。', sections: [{ title: '警告信号', content: '赌博问题通常逐渐发展。' }, { title: '工具和限制', content: '使用博彩公司提供的工具。' }, { title: '在哪里获得帮助', content: '如果你怀疑有赌博问题，可以获得帮助。' }] },
  { id: 20, title: '实践练习', slug: 'practical-exercises-and-appendix', description: '支持学习的练习。', sections: [{ title: '练习1：概率估计', content: '选择10场即将到来的比赛并写下你自己的估计。' }, { title: '练习2：赔率比较', content: '选择5场比赛并比较赔率。' }, { title: '练习3：模拟交易', content: '在投注真钱之前先进行模拟交易。' }, { title: '练习4：日志分析', content: '检查你最近的100次投注。' }] }
]
